site_name: FactorySimPy
site_url: https://factorysimpy.github.io/FactorySimPy/

theme:
  name: material  # optional: for Material Design theme
  #name: readthedocs
  features:
    - navigation.tabs
    - navigation.sections

use_directory_urls: true

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          #paths: ['ReservablePriorityReqStore', 'PriorityReqStore']  # Specify the paths to your modules here
          paths: 
          - src/factorysimpy/base
          
markdown_extensions:
  - admonition
  - codehilite
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences  # (important for code blocks inside lists/admonitions)

nav:
  - Home: index.md  
  - Getting Started: getting_started.md
  - Extended resources: extendedresources.md 
  - API Reference:  
      - ReservablePriorityReqStore: reservablepriorityreqstore.md
      - PriorityReqStore: priorityreqstore.md