site_name: FactorySimPy
site_url: https://factorysimpy.github.io/FactorySimPy/

theme:
  #name: material  # optional: for Material Design theme
  name: readthedocs
  features:
    #- navigation.tabs
    - navigation.expand

use_directory_urls: true

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          #paths: ['ReservablePriorityReqStore', 'PriorityReqStore']  # Specify the paths to your modules here
          paths: 
          - src
          
          
          
          
markdown_extensions:
  - admonition
  - codehilite
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences  # (important for code blocks inside lists/admonitions)

nav:
  - Overview: index.md  
  - Getting Started: getting_started.md
  - Basic Components: basic_components.md 


  - Examples: examples.md
  - Other features:
    - Monitoring and Measurement: monitoring.md
    - Extending Components: extending_components.md
    - Modeling interrupts: interrupts.md
    - Enabling real-time simulation: RTsimulation.md     
  - Supporting classes: 
      - extendedresources.md  
      -  reservablepriorityreqstore.md
      -  priorityreqstore.md
      -  reservablepriorityreqfilterstore.md

  
  - API Reference: api_ref_main_page.md

  
          
  - About: about.md