site_name: FactorySimPy
repo_url: https://github.com/FactorySimPy/FactorySimPy
site_url: https://factorysimpy.github.io/FactorySimPy/
extra_css:
  - extra.css

theme:
  #name: material  # optional: for Material Design theme
  name: readthedocs
  features:
    #- navigation.tabs
    - navigation.expand

use_directory_urls: true


plugins:
  - search
  - mermaid2
  - mkdocstrings:
      handlers:
        python:
          #paths: ['ReservablePriorityReqStore', 'PriorityReqStore']  # Specify the paths to your modules here
          options:
            docstring_style: google
            docstring_section_style: table
            show_source: true
            source_linker: mkdocstrings.handlers.python.rendering.SourceLinker
            source_url_template: https://github.com/FactorySimPy/FactorySimPy/blob/main/{path}#L{linenno}
            show_root_toc: true
            show_root_heading: true
            show_root_full_path: false
            show_object_full_path: false
            heading_level: 2
            show_submodules: true
            inherited_members: false
            show_if_no_docstring: false
            merge_init_into_class: true
          paths: ["src"]         
markdown_extensions:
  - admonition
  - codehilite
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
nav:
  - Overview: index.md  
  - Getting Started: getting_started.md
  - SYSTEM DESCRIPTION:
    - Basic Components: basic_components.md 
    - Examples: examples.md
    - Other features:
      - Monitoring and Measurement: monitoring.md
      - Constructs for Modeling: constructs.md
      - Extending Components: extending_components.md
      - Modeling interrupts: interrupts.md
      - Enabling real-time simulation: RTsimulation.md     
  - REFERENCE:
    - Supporting classes: extendedresources.md  
    - API Reference: api_ref_main_page_2.md

  
  - About:       
    - Authors: authors.md
    - Changelog: changelog.md
    - License: license.md
    